### ISSUE TITLE
Unused import from wildcard import found

### ISSUE THREAD

**Issue by VFXGamer** [Kannampuzha/Paint#7]
https://github.com/Kannampuzha/Paint/blob/c9186f65cdf5e446d58014c054bad87bbb61f857/paint_app.py#L2

You can Import specific parts of the module instead of whole.

**Comment by Kannampuzha** [comment]
i am lazy

**Comment by VFXGamer** [comment]
Mark it for beginners so if someone is interested can make changes and send a pull request.

**Comment by Kannampuzha** [comment]
how to do that

**Comment by VFXGamer** [comment]
On PC,
See on your right side there will be few tabs among which you have to go in
the **labels** menu, select the one you feel is most appropriate.
